# ============================================
# Render Blueprint Configuration
# Full-Stack Monorepo Deployment (Docker)
# ============================================

services:
  # ---------- Backend Service ----------
  - type: web
    name: diabetes-backend
    runtime: docker
    region: oregon
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile.backend
    dockerContext: ./
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: ENV
        value: production
      # Inject the frontend URL after it’s deployed (optional)
      - key: FRONTEND_URL
        fromService:
          type: web
          name: diabetes-frontend
          envVarKey: RENDER_EXTERNAL_URL

  # ---------- Frontend Service ----------
  - type: web
    name: diabetes-frontend
    runtime: docker
    region: oregon
    plan: free
    rootDir: frontend
    dockerfilePath: ./Dockerfile.frontend
    dockerContext: ./
    autoDeploy: true
    envVars:
      # Automatically inject backend public URL into frontend container
      - key: API_BASE_URL
        fromService:
          type: web
          name: diabetes-backend
          envVarKey: RENDER_EXTERNAL_URL
